obj-$(CONFIG_SENSORS_SSC)		+= sensors_ssc.o
obj-$(CONFIG_SENSORS)			+= sensors_class.o

obj-$(CONFIG_SENSORS_CM36672P_IRIS)	+= cm36672p_iris.o
obj-$(CONFIG_SENSORS_SX9310)		+= sx9310.o
obj-$(CONFIG_SENSORS_SX9320)		+= sx9320.o
obj-$(CONFIG_SENSORS_SX9320_WIFI)	+= sx9320_wifi.o
obj-$(CONFIG_SENSORS_SX9320_WIFI_SUB)	+= sx9320_wifi_sub.o

obj-$(CONFIG_SENSORS_MAX86900)		+= max86900.o
obj-$(CONFIG_SENSORS_MAX86902)		+= max86902.o
obj-$(CONFIG_SENSORS_MAX_NOTCHFILTER)	+= max_notchfilter/

obj-$(CONFIG_SENSORS_HRM_MAX86902)	+= hrm_max86902.o
obj-$(CONFIG_SENSORS_HRM_ADPD143)	+= hrm_adpd143.o
obj-$(CONFIG_SENSORS_HRMSENSOR)		+= hrmsensor.o