
#
# panel object
# namd : samsung_dsi_panel_"DDI NAME"_"PANEL NAME".c
#
obj-y  += ss_dsi_panel_ANA38401_AMS968HH01.o

#
# smart dimming function
#
obj-y  += ss_dsi_smart_dimming_ANA38401_AMS968HH01.o
