#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#
obj-y  += ss_dsi_panel_S6E3HA6_AMS622MR01.o
obj-y  += ss_dsi_smart_dimming_S6E3HA6_AMS622MR01.o
obj-y  += ss_dsi_active_clk_S6E3HA6.o
obj-y  += ss_dsi_poc_S6E3HA6.o