#
# Samsung Common file.
#

obj-y += ss_dsi_panel_sysfs.o
obj-y += ss_dsi_panel_debug.o
obj-y += ss_dsi_panel_common.o
obj-y += ss_dsi_mdnie_lite_common.o
obj-y += ss_dsi_smart_dimming_common.o
obj-$(CONFIG_SAMSUNG_DEBUG_DISPLAY) += dlog.o
obj-$(CONFIG_DISPLAY_USE_INFO) += ss_dpui_common.o

# TO SUPPORT SPI INTERFACE
obj-y  += ss_ddi_spi_common.o

#
# panel directory make file
#

# TO SUPPORT PBA BOOINT
obj-y += PBA_BOOTING/

# DREAM DSC panel
obj-$(CONFIG_PANEL_S6E3HA6_AMB577MQ01_WQHD) += S6E3HA6_AMB577MQ01/

# DREAM2 DSC panel
obj-$(CONFIG_PANEL_S6E3HA6_AMS622MR01_WQHD) += S6E3HA6_AMS622MR01/

# GREAT DSC panel
obj-$(CONFIG_PANEL_S6E3HA6_AMB632NF01_WQHD) += S6E3HA6_AMB632NF01/

# KELLY panel
obj-$(CONFIG_PANEL_S6E3FA5_AMS420MS01_FHD) += S6E3FA5_AMS420MS01/

# KELLY panel
obj-$(CONFIG_PANEL_S6E3FA5_AMS420QW01_FHD) += S6E3FA5_AMS420QW01/

# KELLY panel
obj-$(CONFIG_PANEL_S6E3FA5_AMS420MS07_FHD) += S6E3FA5_AMS420MS07/

# TAB S3 panel
obj-$(CONFIG_PANEL_ANA38401_AMS968HH01_QXGA) += ANA38401_AMS968HH01/

# TAB S4 panel
obj-$(CONFIG_PANEL_ANA38401_AMSA05RB01_WQXGA) += ANA38401_AMSA05RB01/
